blank_issues_enabled: True
contact_links:
  - name: Discord
    url: https://discord.gg/buMxnnPvTb
    about: Join us on Discord for questions, support and discussions.
  - name: Unity Multiplayer Forum
    url: https://forum.unity.com/forums/multiplayer.26/
    about: Create a thread in the Unity Multiplayer Forum.